<?xml version="1.0" encoding="utf-8"?><Database Name="DiagonesticDb" Class="DiagnosticDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PROSANTO-PC;Initial Catalog=DiagonesticDb;Integrated Security=True" SettingsObjectName="DiagnosticApps.Properties.Settings" SettingsPropertyName="DiagonesticDbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_Category" Member="tbl_Categories">
    <Type Name="tbl_Category">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Test" Member="tbl_Tests">
    <Type Name="tbl_Test">
      <Column Name="TestID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TestNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RoomNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>